### ISSUE TITLE
HTTP Layer

### ISSUE THREAD

**Issue by Dragmoria** [Dragmoria/vintage-for-life-routing#36]
HTTP request layer

Doel is om het mogelijk te maken te volgende request types te kunnen sturen naar onze api vanuit de client:

POST
GET
PATCH
DELETE
PUT

Zou mooi zijn als we vanuit de verschillende javafx controllers een request kunnen maken. 

Misschien iets zoals HTTPUtil.post(url, requestbody);

Javafx zal hier standaard wel wat voor hebben maar ook leuke uitdaging om dat zelf te doen.

**Comment by BasWindesheim** [comment]
`<dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
      <version>2.15.2</version>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-core</artifactId>
      <version>2.15.2</version>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-annotations</artifactId>
      <version>2.15.2</version>
    </dependency>`
    
    
    
    *Toegevoegt aan de pom*
